// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnT6PSoTQs2mbADSqP5DxpGGlsLU649CU',
    appId: '1:60111958732:web:dfc1dd4e109bdcacca4869',
    messagingSenderId: '60111958732',
    projectId: 'liaris-gamer-club',
    authDomain: 'liaris-gamer-club.firebaseapp.com',
    storageBucket: 'liaris-gamer-club.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_obdmAsuvCWMixQLJHOoITvVW-X5OJy4',
    appId: '1:60111958732:android:8adedbedaa86ea8cca4869',
    messagingSenderId: '60111958732',
    projectId: 'liaris-gamer-club',
    storageBucket: 'liaris-gamer-club.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA-WszSj9FYwTbsUtECUDBewkjtVH4rgY',
    appId: '1:60111958732:ios:7c41eccd1789f5e6ca4869',
    messagingSenderId: '60111958732',
    projectId: 'liaris-gamer-club',
    storageBucket: 'liaris-gamer-club.firebasestorage.app',
    iosBundleId: 'com.liarisknight.gamerClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA-WszSj9FYwTbsUtECUDBewkjtVH4rgY',
    appId: '1:60111958732:ios:7c41eccd1789f5e6ca4869',
    messagingSenderId: '60111958732',
    projectId: 'liaris-gamer-club',
    storageBucket: 'liaris-gamer-club.firebasestorage.app',
    iosBundleId: 'com.liarisknight.gamerClub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnT6PSoTQs2mbADSqP5DxpGGlsLU649CU',
    appId: '1:60111958732:web:5e145706d1bd768bca4869',
    messagingSenderId: '60111958732',
    projectId: 'liaris-gamer-club',
    authDomain: 'liaris-gamer-club.firebaseapp.com',
    storageBucket: 'liaris-gamer-club.firebasestorage.app',
  );
}
